seed: 42

classes:
  arabic_moroccan: 0
  arabizi_moroccan: 1
  other: 2

final_dataset:
  fields:
    - text
    - dialect
    - src
    - has_latin_script
    - label
  deduplicate_on: text


sources:
    n_dataset: 5
    dataset0: atlasia/Darija_LID_Anootation_10k
    dataset1: atlasia/DODa-audio-dataset
    dataset2: atlasia/Darija-LID
    dataset3: UBC-NLP/alexandria
    dataset4: https://huggingface.co/datasets/atlasia/levantine_dialects
